
CREATE TABLE platform_preferences (
  user_id    UUID    NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  instagram  BOOLEAN NOT NULL DEFAULT FALSE,
  facebook   BOOLEAN NOT NULL DEFAULT FALSE,
  tiktok     BOOLEAN NOT NULL DEFAULT FALSE,
  twitter    BOOLEAN NOT NULL DEFAULT FALSE,
  linkedin   BOOLEAN NOT NULL DEFAULT FALSE,
  youtube    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
